labels:
  "✨ Feature":
    - '^feat\b.*'
    - '^feature\b.*'
    - '^add\b.*'

  "🐞 BugFix":
    - '^fix\b.*'

  "📄 Docs":
    - '^docs\b.*'

  "🧹 Chore":
    - '^chore\b.*'

  "🪄 Modify":
    - '^modify\b.*'
    - '^rename\b.*'
    - '^correct\b.*'

  "🎨 UI":
    - '^design\b.*'
    - '^ui\b.*'

  "🧚 Style":
    - '^style\b.*'

  "❄️ Release":
    - '^merge\b.*'

  "⚙️ Setting":
    - '^setting\b.*'

  "🛠️ Refactor":
    - '^refactor\b.*'

  "⚡️ Performance":
    - '^perf\b.*'
    - '^performance\b.*'

  "🧪 Test":
    - '^test\b.*'

  "🔥 Hotfix":
    - '^hotfix\b.*'
